#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qds167337249_db")]
	public partial class aliDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertProductListing(ProductListing instance);
    partial void UpdateProductListing(ProductListing instance);
    partial void DeleteProductListing(ProductListing instance);
    partial void InsertSearch_KeyWords(Search_KeyWords instance);
    partial void UpdateSearch_KeyWords(Search_KeyWords instance);
    partial void DeleteSearch_KeyWords(Search_KeyWords instance);
    #endregion
		
		public aliDataContext() : 
				base(global::DataCenter.Properties.Settings.Default.qds167337249_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public aliDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aliDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aliDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public aliDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductListing> ProductListing
		{
			get
			{
				return this.GetTable<ProductListing>();
			}
		}
		
		public System.Data.Linq.Table<Search_KeyWords> Search_KeyWords
		{
			get
			{
				return this.GetTable<Search_KeyWords>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductListing")]
	public partial class ProductListing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _CreateYear;
		
		private int _CreateMonth;
		
		private int _CreateDay;
		
		private System.DateTime _CreateTime;
		
		private int _ProductOrder;
		
		private string _CompanyName;
		
		private decimal _PriceFrom;
		
		private decimal _PriceTo;
		
		private int _Feedback;
		
		private int _OrdersQty;
		
		private string _ProudctLink;
		
		private int _KeyWordsId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCreateYearChanging(int value);
    partial void OnCreateYearChanged();
    partial void OnCreateMonthChanging(int value);
    partial void OnCreateMonthChanged();
    partial void OnCreateDayChanging(int value);
    partial void OnCreateDayChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnProductOrderChanging(int value);
    partial void OnProductOrderChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnPriceFromChanging(decimal value);
    partial void OnPriceFromChanged();
    partial void OnPriceToChanging(decimal value);
    partial void OnPriceToChanged();
    partial void OnFeedbackChanging(int value);
    partial void OnFeedbackChanged();
    partial void OnOrdersQtyChanging(int value);
    partial void OnOrdersQtyChanged();
    partial void OnProudctLinkChanging(string value);
    partial void OnProudctLinkChanged();
    partial void OnKeyWordsIdChanging(int value);
    partial void OnKeyWordsIdChanged();
    #endregion
		
		public ProductListing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateYear", DbType="Int NOT NULL")]
		public int CreateYear
		{
			get
			{
				return this._CreateYear;
			}
			set
			{
				if ((this._CreateYear != value))
				{
					this.OnCreateYearChanging(value);
					this.SendPropertyChanging();
					this._CreateYear = value;
					this.SendPropertyChanged("CreateYear");
					this.OnCreateYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateMonth", DbType="Int NOT NULL")]
		public int CreateMonth
		{
			get
			{
				return this._CreateMonth;
			}
			set
			{
				if ((this._CreateMonth != value))
				{
					this.OnCreateMonthChanging(value);
					this.SendPropertyChanging();
					this._CreateMonth = value;
					this.SendPropertyChanged("CreateMonth");
					this.OnCreateMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDay", DbType="Int NOT NULL")]
		public int CreateDay
		{
			get
			{
				return this._CreateDay;
			}
			set
			{
				if ((this._CreateDay != value))
				{
					this.OnCreateDayChanging(value);
					this.SendPropertyChanging();
					this._CreateDay = value;
					this.SendPropertyChanged("CreateDay");
					this.OnCreateDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductOrder", DbType="Int NOT NULL")]
		public int ProductOrder
		{
			get
			{
				return this._ProductOrder;
			}
			set
			{
				if ((this._ProductOrder != value))
				{
					this.OnProductOrderChanging(value);
					this.SendPropertyChanging();
					this._ProductOrder = value;
					this.SendPropertyChanged("ProductOrder");
					this.OnProductOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceFrom", DbType="Decimal(18,2) NOT NULL")]
		public decimal PriceFrom
		{
			get
			{
				return this._PriceFrom;
			}
			set
			{
				if ((this._PriceFrom != value))
				{
					this.OnPriceFromChanging(value);
					this.SendPropertyChanging();
					this._PriceFrom = value;
					this.SendPropertyChanged("PriceFrom");
					this.OnPriceFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceTo", DbType="Decimal(18,2) NOT NULL")]
		public decimal PriceTo
		{
			get
			{
				return this._PriceTo;
			}
			set
			{
				if ((this._PriceTo != value))
				{
					this.OnPriceToChanging(value);
					this.SendPropertyChanging();
					this._PriceTo = value;
					this.SendPropertyChanged("PriceTo");
					this.OnPriceToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feedback", DbType="Int NOT NULL")]
		public int Feedback
		{
			get
			{
				return this._Feedback;
			}
			set
			{
				if ((this._Feedback != value))
				{
					this.OnFeedbackChanging(value);
					this.SendPropertyChanging();
					this._Feedback = value;
					this.SendPropertyChanged("Feedback");
					this.OnFeedbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdersQty", DbType="Int NOT NULL")]
		public int OrdersQty
		{
			get
			{
				return this._OrdersQty;
			}
			set
			{
				if ((this._OrdersQty != value))
				{
					this.OnOrdersQtyChanging(value);
					this.SendPropertyChanging();
					this._OrdersQty = value;
					this.SendPropertyChanged("OrdersQty");
					this.OnOrdersQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProudctLink", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProudctLink
		{
			get
			{
				return this._ProudctLink;
			}
			set
			{
				if ((this._ProudctLink != value))
				{
					this.OnProudctLinkChanging(value);
					this.SendPropertyChanging();
					this._ProudctLink = value;
					this.SendPropertyChanged("ProudctLink");
					this.OnProudctLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWordsId", DbType="Int NOT NULL")]
		public int KeyWordsId
		{
			get
			{
				return this._KeyWordsId;
			}
			set
			{
				if ((this._KeyWordsId != value))
				{
					this.OnKeyWordsIdChanging(value);
					this.SendPropertyChanging();
					this._KeyWordsId = value;
					this.SendPropertyChanged("KeyWordsId");
					this.OnKeyWordsIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Search_KeyWords")]
	public partial class Search_KeyWords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KeyWords;
		
		private System.DateTime _CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKeyWordsChanging(string value);
    partial void OnKeyWordsChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    #endregion
		
		public Search_KeyWords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWords", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyWords
		{
			get
			{
				return this._KeyWords;
			}
			set
			{
				if ((this._KeyWords != value))
				{
					this.OnKeyWordsChanging(value);
					this.SendPropertyChanging();
					this._KeyWords = value;
					this.SendPropertyChanged("KeyWords");
					this.OnKeyWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
